# Generated by Django 4.1.4 on 2023-01-23 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("template", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SentMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("_from", models.CharField(blank=True, max_length=200, null=True)),
                ("_group", models.CharField(blank=True, max_length=200, null=True)),
                ("_company", models.CharField(blank=True, max_length=200, null=True)),
                ("_body", models.CharField(blank=True, max_length=200, null=True)),
                ("_subject", models.CharField(blank=True, max_length=200, null=True)),
                ("_template", models.CharField(blank=True, max_length=200, null=True)),
                ("_image", models.ImageField(blank=True, null=True, upload_to="media")),
                ("scheduleMail", models.BooleanField(default=False)),
                ("_year", models.IntegerField(blank=True, null=True)),
                ("_month", models.IntegerField(blank=True, null=True)),
                ("_date", models.IntegerField(blank=True, null=True)),
                ("_hour", models.IntegerField(blank=True, null=True)),
                ("_minute", models.IntegerField(blank=True, null=True)),
                ("time", models.DateTimeField(auto_now=True)),
                ("celeryID", models.CharField(blank=True, max_length=200, null=True)),
                ("status", models.CharField(default="PENDING", max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailer.groups",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileUploadForMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="media")),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailer.sentmail",
                    ),
                ),
            ],
        ),
    ]
