# Generated by Django 4.1.4 on 2023-02-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="html_file",
            field=models.FileField(blank=True, null=True, upload_to="media/template"),
        ),
    ]
