# Generated by Django 4.1.4 on 2022-12-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_remove_group_details_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group_details",
            name="name",
        ),
    ]
