# Generated by Django 4.1.4 on 2023-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_sentmail_schedulingmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentmail",
            name="_date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sentmail",
            name="_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sentmail",
            name="_minute",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sentmail",
            name="_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sentmail",
            name="_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sentmail",
            name="scheduleMail",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="SchedulingMail",
        ),
    ]
