# Generated by Django 4.1.4 on 2023-01-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="template",
            field=models.TextField(),
        ),
    ]
