# Generated by Django 4.1.4 on 2023-02-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_template_html_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="template",
            field=models.TextField(default="null"),
        ),
    ]
