# Generated by Django 4.1.4 on 2023-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0003_sentmail__date_sentmail__hour_sentmail__minute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentmail",
            name="_from",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sentmail",
            name="_group",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sentmail",
            name="_subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
