# Generated by Django 4.1.4 on 2023-01-19 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailer", "0003_alter_template_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_from", models.CharField(max_length=200)),
                ("_group", models.CharField(max_length=200)),
                ("_company", models.CharField(max_length=200)),
                ("_body", models.CharField(max_length=200)),
                ("_subject", models.CharField(max_length=200)),
                ("_template", models.CharField(blank=True, max_length=200, null=True)),
                ("_file", models.FileField(blank=True, null=True, upload_to="media")),
                ("_image", models.ImageField(blank=True, null=True, upload_to="media")),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
