# Generated by Django 4.1.4 on 2022-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0003_remove_group_details_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="group_details",
            name="group",
            field=models.IntegerField(default=0),
        ),
    ]
