# Generated by Django 4.1.4 on 2023-01-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0004_alter_sentmail__from_alter_sentmail__group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentmail",
            name="_file",
        ),
        migrations.AddField(
            model_name="sentmail",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="FileUploadForMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="media")),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailer.sentmail",
                    ),
                ),
            ],
        ),
    ]
