# Generated by Django 4.1.4 on 2022-12-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0004_group_details_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group_details",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailer.groups"
            ),
        ),
    ]
