# Generated by Django 4.1.4 on 2023-01-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0004_sentmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentmail",
            name="_body",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sentmail",
            name="_company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
