# Generated by Django 4.1.4 on 2022-12-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0005_alter_group_details_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group_details",
            name="group",
            field=models.IntegerField(),
        ),
    ]
