# Generated by Django 4.1.4 on 2023-01-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0006_schedulingmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentmail",
            name="celeryID",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
