# Generated by Django 4.1.4 on 2023-01-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0007_sentmail_celeryid"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulingmail",
            name="celeryID",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="schedulingmail",
            name="status",
            field=models.CharField(default="Pending", max_length=200),
        ),
        migrations.AddField(
            model_name="sentmail",
            name="status",
            field=models.CharField(default="Pending", max_length=200),
        ),
    ]
