# Generated by Django 4.1.4 on 2023-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0008_schedulingmail_celeryid_schedulingmail_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group_details",
            name="email",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="schedulingmail",
            name="status",
            field=models.CharField(default="PENDING", max_length=200),
        ),
    ]
