version: "3.8"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  redis:
    restart: always
    image: redis:7-alpine

  celery_worker:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A bulkmailer worker -l info
    depends_on:
      - db
      - web
      - redis

  celery_beat:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A bulkmailer.celery beat -l info
    depends_on:
      - db
      - web
      - redis
