# Generated by Django 4.1.4 on 2022-12-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="New_User_Resgistration",
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
