# Generated by Django 4.1.4 on 2023-02-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmail_app_model",
            name="email",
            field=models.CharField(max_length=200),
        ),
    ]
