# Generated by Django 4.1.4 on 2023-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_gmail_app_model_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmail_app_model",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
