# Generated by Django 4.1.4 on 2022-12-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="new_user_resgistration",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="new_user_resgistration",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
