# Generated by Django 4.1.4 on 2023-01-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_gmail_app_model_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmail_app_model",
            name="email",
            field=models.CharField(default=True, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
