# Generated by Django 4.1.4 on 2023-01-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_gmail_app_model_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new_user_resgistration",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Others", "Others")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="new_user_resgistration",
            name="mobile",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
