# Generated by Django 4.1.4 on 2022-12-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_new_user_resgistration_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="new_user_resgistration",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
