# Generated by Django 4.1.4 on 2022-12-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_new_user_resgistration_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new_user_resgistration",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
